#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;
using ll = long long;

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main() {
  int n, q;
  cin >> n >> q;
  string s;
  cin >> s;
  string tmp;
  int sum = 0;
  int pointer = 0;
  for (int i = 0; i < q; i++) {
    int q1;
    int q2;
    cin >> q1 >> q2;
    if (q1 == 1) {
      //   tmp = s.substr(s.size() - q2, q2);
      //   s.erase(s.size() - q2, q2);
      //   s.insert(0, tmp);
      sum += q2;
    } else {
      pointer = (sum % s.size());
      cout << s.at(pointer - 1 + q2 - 1) << endl;
    }
  }

  return 0;
}
