#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


int64_t solve(auto N, const std::vector<auto> &C, auto Q, const std::vector<auto> &S) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, Q;
    std::cin >> N;
    std::vector<auto> C(N);
    REP (i, N) {
        std::cin >> C[i];
    }
    std::cin >> Q;
    std::vector<auto> S(Q);
    REP (i, Q) {
        std::cin >> S[i];
    }
    auto ans = solve(N, C, Q, S);
    std::cout << ans << '\n';
    return 0;
}
