#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


auto solve(long long N, int Q, const std::vector<long long> &T, const std::vector<long long> &X, const std::vector<long long> &Y, const std::vector<long long> &V) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    long long N;
    int Q;
    std::cin >> N >> Q;
    std::vector<long long> T(Q), X(Q), Y(Q), V(Q);
    REP (i, Q) {
        std::cin >> T[i] >> X[i] >> Y[i] >> V[i];
    }
    auto ans = solve(N, Q, T, X, Y, V);
    // failed to analyze output format
    // TODO: edit here
    std::cout << ans << '\n';
    return 0;
}
