#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


auto solve(long long n, int m, const std::vector<long long> &a, const std::vector<long long> &b) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    long long n;
    int m;
    std::cin >> n >> m;
    std::vector<long long> a(m), b(m);
    REP (i, m) {
        std::cin >> a[i] >> b[i];
    }
    auto ans = solve(n, m, a, b);
    REP (i, n) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
