#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;
template <class T>
inline bool chmax(T& a, T b) {
    if (a < b) {
        a = b;
        return true;
    }
    return false;
}
template <class T>
inline bool chmin(T& a, T b) {
    if (a > b) {
        a = b;
        return true;
    }
    return false;
}


auto solve(long long N, int Q, const std::vector<long long> &L, const std::vector<long long> &R, const std::vector<long long> &T) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    long long N;
    int Q;
    std::cin >> N >> Q;
    std::vector<long long> L(Q), R(Q), T(Q);
    REP (i, Q) {
        std::cin >> L[i] >> R[i] >> T[i];
    }
    auto ans = solve(N, Q, L, R, T);
    REP (i, N) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
