#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;

const std::string YES = "Yes";
const std::string NO = "No";
auto solve(int N, int M, const std::vector<std::string> &S, const std::vector<std::string> &T) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    std::cin >> N;
    std::vector<std::string> S(N);
    std::cin >> M;
    std::vector<std::string> T(M);
    REP (i, N) {
        std::cin >> S[i];
    }
    REP (i, M) {
        std::cin >> T[i];
    }
    auto ans = solve(N, M, S, T);
    REP (i, N) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
