#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi = pair<int, int>;

constexpr int64_t MOD = 1000000007;
int cnt[10010][10010] = {0};
int64_t solve(ll H, ll W, ll N, std::vector<std::vector<ll>> &a) {
    // vector<vector<ll>> cnt(H, vector<ll>(W, 0));

    // 初期条件
    cnt[0][0] = 1;
    // const ll MOD = pow(10, 9) + 7;

    REP(i, H) {
        REP(j, W) {
            // cout << a[i][j] << " ";
            // 壁マスならc[i][j]＝０のままにする
            if (a[i][j] == -1) {
                continue;
            }
            // 左と上から遷移する
            if (i > 0) {
                cnt[i][j] += cnt[i - 1][j];
            }
            if (j > 0) {
                cnt[i][j] += cnt[i][j - 1];
            }
            cnt[i][j] %= MOD;
        }
        // cout << endl;
    }
    return cnt[H - 1][W - 1];
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    ll H, W, N;
    std::cin >> H >> W >> N;
    std::vector<ll> r(N);
    std::vector<ll> c(N);
    vector<vector<ll>> a(H, vector<ll>(W, 0));
    REP(i, N) {
        std::cin >> r[i] >> c[i];
        a[r[i] - 1][c[i] - 1] = -1;
    }
    auto ans = solve(H, W, N, a);
    std::cout << ans << '\n';
    return 0;
}
