#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;

constexpr long long MOD = 998244353;
long long solve(long long N, int M, long long K, const std::vector<long long> &u, const std::vector<long long> &v, const std::vector<long long> &w) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    long long N;
    int M;
    long long K;
    std::cin >> N >> M;
    std::vector<long long> u(M), v(M), w(M);
    std::cin >> K;
    REP (i, M) {
        std::cin >> u[i] >> v[i] >> w[i];
    }
    auto ans = solve(N, M, K, u, v, w);
    std::cout << ans << '\n';
    return 0;
}
