#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const long long MOD = 1;

void solve(long long N, long long Q, long long X, std::vector<long long> W, std::vector<long long> K){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long Q;
    std::scanf("%lld", &Q);
    long long X;
    std::scanf("%lld", &X);
    std::vector<long long> W(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &W[i]);
    }
    std::vector<long long> K(Q);
    for(int i = 0 ; i < Q ; i++){
        std::scanf("%lld", &K[i]);
    }
    solve(N, Q, X, std::move(W), std::move(K));
    return 0;
}
