#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi = pair<int, int>;
template <class T>
inline bool chmax(T &a, T b) {
    if (a < b) {
        a = b;
        return true;
    }
    return false;
}
template <class T>
inline bool chmin(T &a, T b) {
    if (a > b) {
        a = b;
        return true;
    }
    return false;
}

int dp[110][110][110] = {0};  // 初期値も初期条件も 0

void solve(int N, int M, const std::vector<long long> &a, const std::vector<long long> &b, const std::vector<long long> &c, const std::vector<long long> &w, const std::vector<long long> &x, const std::vector<long long> &y, const std::vector<long long> &z) {
    // DPループ
    // 0~Nまでの範囲であることに注意
    REP(n, N) {
        for (int i = a[n]; i < 101; ++i) {
            for (int j = b[n]; j < 101; ++j) {
                for (int k = c[n]; k < 101; ++k) {
                    if (dp[i][j][k] > (int)w[n]) break;
                    chmax(dp[i][j][k], (int)w[n]);
                }
            }
        }
    }

    REP(m, M) {
        cout << dp[x[m]][y[m]][z[m]] << '\n';
    }
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    std::cin >> N;
    std::vector<long long> a(N), b(N), c(N), w(N);
    std::cin >> M;
    std::vector<long long> x(M), y(M), z(M);
    REP(i, N) {
        std::cin >> a[i] >> b[i] >> c[i] >> w[i];
    }
    REP(i, M) {
        std::cin >> x[i] >> y[i] >> z[i];
    }
    solve(N, M, a, b, c, w, x, y, z);
    // REP(i, M) {
    //     std::cout << ans[i] << '\n';
    // }
    return 0;
}
