#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


int64_t solve(int N, int64_t X, int64_t Y, const std::vector<int64_t> &x, const std::vector<int64_t> &y) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    int64_t X, Y;
    std::cin >> N;
    std::vector<int64_t> x(N), y(N);
    std::cin >> X >> Y;
    REP (i, N) {
        std::cin >> x[i] >> y[i];
    }
    auto ans = solve(N, X, Y, x, y);
    std::cout << ans << '\n';
    return 0;
}
