#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


auto solve(int D, int64_t L, int N, const std::vector<int64_t> &C, const std::vector<int64_t> &K, const std::vector<int64_t> &F, const std::vector<int64_t> &T) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int D;
    int64_t L;
    int N;
    std::cin >> D;
    std::vector<int64_t> C(D);
    std::cin >> L >> N;
    std::vector<int64_t> K(N), F(N), T(N);
    REP (i, D) {
        std::cin >> C[i];
    }
    REP (i, N) {
        std::cin >> K[i] >> F[i] >> T[i];
    }
    auto ans = solve(D, L, N, C, K, F, T);
    REP (i, N) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
