#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi = pair<int, int>;

auto solve(long long N, std::string S) {
    vector<ll> count(26);  // アルファベット
    string A = "abcdefghijklmnopqrstuvwxyz";
    ll c = 0;
    string b = " ";

    REP(i, N) {
        ll it = A.find(S[i]);
        if (A[it] != b[0]) {
            c = 0;
        }
        c++;
        b = A[it];
        count[it] = max(count[it]++, c);
    }

    int sum = std::accumulate(count.begin(), count.end(), 0);
    return sum;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    long long N;
    std::string S;
    std::cin >> N;
    std::cin >> S;
    auto ans = solve(N, S);
    cout << ans << '\n';
    return 0;
}
