#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


auto solve(long long N, int Q, std::string S, const std::vector<long long> &l, const std::vector<long long> &r) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    long long N;
    int Q;
    std::string S;
    std::cin >> N >> Q;
    std::vector<long long> l(Q), r(Q);
    std::cin >> S;
    REP (i, Q) {
        std::cin >> l[i] >> r[i];
    }
    auto ans = solve(N, Q, S, l, r);
    REP (i, Q) {
        std::cout << a[i] << '\n';
    }
    return 0;
}
