#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;

const std::string YES = "Yes";
const std::string NO = "No";
auto solve(int N, long long T, const std::vector<long long> &AX, const std::vector<long long> &AY, const std::vector<long long> &BX, const std::vector<long long> &BY) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    long long T;
    std::cin >> N;
    std::vector<long long> AX(N), AY(N), BX(N), BY(N);
    std::cin >> T;
    REP (i, N) {
        std::cin >> AX[i] >> AY[i];
    }
    REP (i, N) {
        std::cin >> BX[i] >> BY[i];
    }
    auto ans = solve(N, T, AX, AY, BX, BY);
    std::cout << Yes << '\n';
    REP (i, N) {
        std::cout << D[i] << ' ';
    }
    std::cout << '\n';
    return 0;
}
