#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


auto solve(int N, int M, int K, const std::vector<long long> &H, const std::vector<long long> &C, const std::vector<long long> &A, const std::vector<long long> &B) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M, K;
    std::cin >> N;
    std::vector<long long> H(N);
    std::cin >> M;
    std::vector<long long> A(M), B(M);
    std::cin >> K;
    std::vector<long long> C(K);
    REP (i, N) {
        std::cin >> H[i];
    }
    REP (i, K) {
        std::cin >> C[i];
    }
    REP (i, M) {
        std::cin >> A[i] >> B[i];
    }
    auto ans = solve(N, M, K, H, C, A, B);
    REP (i, N) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
