#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


auto solve(int a, int b, const std::vector<long long> &c, const std::vector<long long> &d, const std::vector<long long> &e) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int a, b;
    std::cin >> a;
    std::vector<long long> c(a);
    std::cin >> b;
    std::vector<long long> d(b), e(b);
    REP (i, a) {
        std::cin >> c[i];
    }
    REP (i, b) {
        std::cin >> d[i] >> e[i];
    }
    auto ans = solve(a, b, c, d, e);
    REP (i, b) {
        std::cout << f[i] << '\n';
    }
    return 0;
}
