#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi = pair<int, int>;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    ll N, L, R;
    std::cin >> N >> L >> R;
    std::vector<long long> A(N, 0);
    ll before;
    ll a;
    ll mini = 1e9 + 10;
    ll x;
    vector<ll> num(R - L + 1, 0);
    ll ini = R - L + 1;
    ll ok = ini;
    ll ng = -1;
    ll mid;
    for (long long i = 0; i < R - L + 1; ++i) {
        num[i] = i + L;
    }
    bool not_find = true;
    ll diff = 0;
    for (int i = 0; i < N; ++i) {
        std::cin >> a;
        ll target = a;
        not_find = true;
        diff = 0;

        while (not_find) {
            ok = ini;
            ng = -1;

            // cout << "a" << a << endl;
            while (abs(ok - ng) > 1) {
                mid = (ok + ng) / 2;
                if (num[mid] >= target + diff) {
                    ok = mid;
                } else {
                    ng = mid;
                }
            }
            // if (ok == ini) {
            //     // cout << "not found";
            //     // diff++;
            // } else {
            //     not_find = false;
            //     cout << num[ok];
            //     break;
            // }
            // ok = ini;
            // ng = -1;
            // if (not_find) {
            //     while (abs(ok - ng) > 1) {
            //         mid = (ok + ng) / 2;
            //         if (num[mid] >= target - diff) {
            //             ok = mid;
            //         } else {
            //             ng = mid;
            //         }
            //     }
            // }
            // if (ok == ini) {
            //     // cout << "not found";
            // } else {
            //     not_find = false;
            //     cout << num[ok];
            //     break;
            // }
            // diff++;
        }
        if (i != N - 1) {
            cout << " ";
        }
    }
    cout << endl;

    return 0;
}
