#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi = pair<int, int>;

void solve(int64_t N, int M, const std::vector<int64_t> &A) {
    // B[k]:子供kが食べた寿司のおいしさの最大値-1倍
    vector<ll> B(N, 0);
    for (const auto &a : A) {
        // 寿司を食べる子供を二分探索で探す
        decltype(B)::iterator k = upper_bound(B.begin(), B.end(), (-1 * a));
        // REP(i, N) {
        //     cout << B[i] << " ";
        // }
        // cout << endl;
        // cout << (-1 * a) << endl;
        ll index = distance(B.begin(), k);

        if (index == N) {
            cout << -1 << endl;
        } else {
            cout << index + 1 << endl;
            // cout << "k: " << *k << endl;
            // cout << "index: " << index << endl;
            B[index] = -1 * a;
        }
    }
    return;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    int M;
    std::cin >> N >> M;
    std::vector<int64_t> a(M);
    REP(i, M) {
        std::cin >> a[i];
    }
    solve(N, M, a);
    // REP(i, M) {
    //     std::cout << ans[i] << '\n';
    // }
    return 0;
}
