#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


auto solve(int N, int Q, const std::vector<long long> &A, const std::vector<long long> &L, const std::vector<long long> &R, const std::vector<long long> &V) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, Q;
    std::cin >> N;
    std::vector<long long> A(N);
    std::cin >> Q;
    std::vector<long long> L(Q), R(Q), V(Q);
    REP (i, N) {
        std::cin >> A[i];
    }
    REP (i, Q) {
        std::cin >> L[i] >> R[i] >> V[i];
    }
    auto ans = solve(N, Q, A, L, R, V);
    REP (i, Q) {
        std::cout << a[i] << '\n';
    }
    return 0;
}
