#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi = pair<int, int>;

ll dp[410][410] = {0};
int flag[410][410] = {false};
int N;
ll a[410];
const ll INF = 1e18;

ll rec(int l, int r) {
    if (flag[l][r]) return dp[l][r];
    flag[l][r] = true;
    if (l == r) return 0;
    ll fans = INF;
    REP3(m, l, r) {
        fans = min(fans, rec(l, m) + rec(m + 1, r));
    }
    ll sum = 0;
    for (int i = l; i < r + 1; ++i) {
        sum += a[i];
    }
    return dp[l][r] = fans + sum;
}

int64_t solve() {
    return rec(1, N);
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    std::cin >> N;
    REP(i, N) {
        std::cin >> a[i + 1];
    }
    auto ans = solve();
    std::cout << ans << '\n';
    return 0;
}
