#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;

const std::string YES = "Yes";
const std::string NO = "No";
auto solve(long long N, int M, int Q, const std::vector<long long> &X, const std::vector<long long> &Y, const std::vector<long long> &A, const std::vector<long long> &B) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    long long N;
    int M, Q;
    std::cin >> N >> M;
    std::vector<long long> X(M), Y(M);
    std::cin >> Q;
    std::vector<long long> A(Q), B(Q);
    REP (i, M) {
        std::cin >> X[i] >> Y[i];
    }
    REP (i, Q) {
        std::cin >> A[i] >> B[i];
    }
    auto ans = solve(N, M, Q, X, Y, A, B);
    REP (i, Q) {
        std::cout << a[i] << '\n';
    }
    return 0;
}
