#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi = pair<int, int>;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    ll N, L;
    cin >> N >> L;
    vector<ll> A(N);
    REP(i, N) {
        cin >> A[i];
    }

    sort(A.begin(), A.end());
    bool on = false;
    REP(i, N) {
        if (A[i] < L) {
            continue;
        } else {
            cout << N - i << endl;
            on = true;
            break;
        }
    }
    if (!on) {
        cout << 0 << endl;
    }

    return 0;
}
