#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi =  pair<int, int>;


auto solve(int N, const std::vector<long long> &C, const std::vector<long long> &P, int Q, const std::vector<long long> &L, const std::vector<long long> &R) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, Q;
    std::cin >> N;
    std::vector<long long> C(N), P(N);
    REP (i, N) {
        std::cin >> C[i] >> P[i];
    }
    std::cin >> Q;
    std::vector<long long> L(Q), R(Q);
    REP (i, Q) {
        std::cin >> L[i] >> R[i];
    }
    auto ans = solve(N, C, P, Q, L, R);
    REP (i, Q) {
        std::cout << A[i] << ' ' << B[i] << '\n';
    }
    return 0;
}
