#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
using pi = pair<int, int>;

const std::string FIRST = "First";
const std::string SECOND = "Second";
// https://qiita.com/drken/items/4e1bcf8413af16cb62da#2-2-%E3%82%B2%E3%83%BC%E3%83%A0%E8%A7%A3%E6%9E%90%E3%81%AE%E4%BE%8B

bool dp[100010] = {false};

bool solve(int N, int64_t K, const std::vector<int64_t> &a) {
    // DPループ
    REP(i, K + 1) {
        REP(j, N) {
            if (i - a[j] >= 0) {
                dp[i] |= !dp[i - a[j]];
            }
        }
    }
    return dp[K];
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    int64_t K;
    std::cin >> N;
    std::vector<int64_t> a(N);
    std::cin >> K;
    REP(i, N) {
        std::cin >> a[i];
    }
    auto ans = solve(N, K, a);
    std::cout << (ans ? FIRST : SECOND) << '\n';
    return 0;
}
