#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using ll = long long;
#define rep(i, n) for (int i = 0; (i) < (n); ++(i))

const std::string YES = "POSSIBLE";
const std::string NO = "IMPOSSIBLE";
bool solve(int64_t N, int M, const std::vector<int64_t> &a, const std::vector<int64_t> &b) {
  // TODO: edit here
  // グラフは隣接リストとして保持する
  vector<vector<int>> G(N);
  rep(i, M) {
    // cout << a[i] << " " << b[i] << endl;
    G[a[i] - 1].push_back(b[i] - 1);
    G[b[i] - 1].push_back(a[i] - 1);
  }
  /*
  グラフ上で幅優先探索を行い頂点0から各頂点への距離を求める
  */
  vector<int> dist(N, -1);  //-1は未訪問

  // 幅優先探索で扱うキュー
  queue<int> Q;

  // 始点となる頂点には0を入れておく
  Q.push(0);

  // 始点となる頂点への最短距離は0とする
  dist[0] = 0;

  // 幅優先探索で各頂点への最短距離を求める
  ll i;
  rep(i, G.size()) {
    // rep(j, G[i].size()) {
    //   cout << G[i][j] << " ";
    // }
    // cout << endl;
  }
  while (Q.size() > 0) {
    // キューの先頭の頂点を取り出してiとする
    i = Q.front();
    Q.pop();
    // 頂点に隣接してい頂点を順番に見る
    // 見ている頂点をjとする
    // cout << "i:" << i << endl;
    rep(j, G[i].size()) {
      // jが未訪問だったとき
      if (dist[G[i][j]] == -1) {
        dist[G[i][j]] = dist[i] + 1;
        Q.push(G[i][j]);
      }
    }
  }

  if (dist[N - 1] == 2) {
    return true;
  } else {
    return false;
  }
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  //   std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t N;
  int M;
  std::cin >> N >> M;
  std::vector<int64_t> a(M), b(M);
  REP(i, M) {
    std::cin >> a[i] >> b[i];
  }
  auto ans = solve(N, M, a, b);
  std::cout << (ans ? YES : NO) << '\n';
  return 0;
}